# Generated by Django 3.1.7 on 2021-06-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_notes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
